export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAILURE = 'FETCH_PHONES_FAILURE';

export const PHONES_ADDED_TO_CART = 'PHONES_ADDED_TO_CART';
export const PHONES_REMOVED_FROM_CART = 'PHONES_REMOVED_FROM_CART';
